service: metar-weather

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 60
  stage: dev
  region: us-east-1
  environment:
    AVWX_TOKEN: XXXXXXXXXXXXXXX

functions:
  lambda:
    name: metar-weather
    handler: index.metarWeather
    events:
      - http:
          path: ''
          method: get
          cors: true
      - http:
          path: ''
          method: post
          cors: true
